# Generated by Django 4.0.2 on 2022-05-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotationSystemApp', '0002_input'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('phone', models.CharField(default=None, max_length=100, verbose_name='phone')),
            ],
        ),
    ]
