# Generated by Django 4.0.2 on 2022-05-09 23:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quotationSystemApp', '0003_client'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Input',
            new_name='Item',
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('price', models.FloatField(default=0, verbose_name='price')),
                ('total', models.FloatField(default=0, verbose_name='total')),
                ('date', models.DateTimeField(default=django.utils.timezone.localdate, verbose_name='date')),
                ('time', models.TimeField(default=django.utils.timezone.localtime, verbose_name='time')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotationSystemApp.client')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotationSystemApp.item')),
            ],
        ),
    ]
