# Generated by Django 4.0.2 on 2022-05-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotationSystemApp', '0007_alter_quotation_discount_alter_quotation_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='iva',
            field=models.IntegerField(default=19, verbose_name='iva'),
        ),
    ]
