# Generated by Django 4.0.2 on 2022-05-12 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotationSystemApp', '0008_alter_quotation_discount_alter_quotation_iva'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsQuotation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('total', models.FloatField(default=0, verbose_name='total')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotationSystemApp.item')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotationSystemApp.quotation')),
            ],
        ),
    ]
