# Generated by Django 4.0.2 on 2022-05-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotationSystemApp', '0009_itemsquotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='subtotal',
            field=models.FloatField(default=0, verbose_name='subtotal'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='totalIva',
            field=models.FloatField(default=0, verbose_name='totalIva'),
        ),
    ]
