# Generated by Django 4.0.2 on 2022-05-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotationSystemApp', '0011_quotation_totaldiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsquotation',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='itemsquotation',
            name='price',
            field=models.FloatField(default=0, verbose_name='price'),
        ),
    ]
