# Generated by Django 4.0.2 on 2022-05-18 03:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotationSystemApp', '0012_itemsquotation_name_itemsquotation_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='dateTime',
            field=models.DateTimeField(default=datetime.date(2022, 5, 17)),
        ),
    ]
