# Generated by Django 4.0.2 on 2022-06-09 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotationSystemApp', '0013_alter_quotation_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='observation',
            field=models.TextField(default='', verbose_name='observation'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='dateTime',
            field=models.DateTimeField(default=datetime.date(2022, 6, 9)),
        ),
    ]
