# Generated by Django 4.0.2 on 2022-06-09 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotationSystemApp', '0014_quotation_observation_alter_quotation_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='observation',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='observation'),
        ),
    ]
