# Generated by Django 4.0.2 on 2022-06-14 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotationSystemApp', '0015_alter_quotation_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='dateTime',
            field=models.DateTimeField(default=datetime.date(2022, 6, 14)),
        ),
    ]
