# Generated by Django 4.0.2 on 2022-08-04 13:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotationSystemApp', '0017_alter_itemsquotation_name_alter_quotation_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='dateTime',
            field=models.DateTimeField(default=datetime.date(2022, 8, 4)),
        ),
        migrations.CreateModel(
            name='BillingStatement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quotation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotationSystemApp.quotation')),
            ],
        ),
    ]
