# Generated by Django 4.0.2 on 2022-08-10 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotationSystemApp', '0018_alter_quotation_datetime_billingstatement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingstatement',
            old_name='quotation_id',
            new_name='quotation',
        ),
        migrations.AlterField(
            model_name='quotation',
            name='dateTime',
            field=models.DateTimeField(default=datetime.date(2022, 8, 10)),
        ),
    ]
